[package]
name = "ri-trace-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
reqwest.workspace = true
ri-core = { path = "../ri-core" }
rusqlite.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
