pid /tmp/nginx.pid;
events {}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    server {
        listen 8443 ssl;
        http2 on;
        server_name _;
        ssl_certificate /tls/server.crt;
        ssl_certificate_key /tls/server.key;
        ssl_client_certificate /tls/ca.crt;
        ssl_verify_client on;
        ssl_protocols TLSv1.2 TLSv1.3;

        location = /Blockchain/GetBlockNumber {
            grpc_pass grpc://@@NORN_NODE_HOSTNAME@@:45555;
        }
        location = /Blockchain/GetBlockByNumber {
            grpc_pass grpc://@@NORN_NODE_HOSTNAME@@:45555;
        }
        location = /Blockchain/ReadContractAddress {
            grpc_pass grpc://@@NORN_NODE_HOSTNAME@@:45555;
        }
        location / {
            return 403;
        }
    }
}
