[package]
name = "ri-chain-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
hex.workspace = true
prost.workspace = true
reqwest.workspace = true
ri-core = { path = "../ri-core" }
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
axum.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true

[lints]
workspace = true
